config/routes.rb
Rails.application.routes.draw do
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match '/auth/failure', to: redirect('/'), via: [:get, :post]

  get '/disclaimer' => 'countdowns#disclaimer', as: 'disclaimer'

  match '/new' => 'countdowns#new', as: 'new_countdown', via: [:get, :post]
  get '/:id' => 'countdowns#show', as: 'countdown'
  post '/' => 'countdowns#create', as: 'countdowns'
  match '/:id' => 'countdowns#update', via: [:patch, :put]
  delete '/:id/destroy' => 'countdowns#destroy'
  get '/:id/edit' => 'countdowns#edit', as: 'edit_countdown'

  root :to => 'countdowns#index'
end

app/models/countdown.rb
class Countdown < ActiveRecord::Base
	validates_uniqueness_of :name, :case_sensitive => false
	before_save :before_save

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ':placeholder'
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	validates :image, :attachment_presence => true
	validates_with AttachmentPresenceValidator, :attributes => :image
	validates_with AttachmentSizeValidator, :attributes => :image, :less_than => 10.megabytes

	def before_save
		name.downcase!
	end
	
	def tweets
		client = Twitter::REST::Client.new do |config|
			config.consumer_key        = ENV["TWITTER_CONSUMER_KEY"]
			config.consumer_secret     = ENV["TWITTER_CONSUMER_SECRET"]
		end

		i = 0

		begin
			client.search("\##{hashtag}", :result_type => "recent").take(25).collect do |tweet|
				{:name => "#{tweet.user.screen_name}", :text => "#{tweet.text}"}
			end
		rescue Twitter::Error => error
			i += 1
			retry if i < 2
			[]
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :signed_in?
  before_action :set_locale
  before_action :set_site

  def set_site
    case request.domain
    when "ctfi.cc", "ctfi.dev"
      @site = "CTFI"
    else 
      @site = "GTFO"
    end
  end
 
  def set_locale
  	case request.domain
  	when "ctfi.cc", "ctfi.dev"
  		I18n.locale = "en-CTFI"
  	else 
  		I18n.locale = I18n.default_locale
  	end
  end

  def user_required
    redirect_to '/auth/twitter?force_login=true' unless signed_in?
  end

  def signed_in?
    session[:username].present?
  end
end

app/controllers/countdowns_controller.rb
class CountdownsController < ApplicationController
  before_filter :user_required, only: [:new, :create, :edit, :update, :destory]

  def index
    @countdowns = Countdown.where('start_date < ?', DateTime.now).where('end_date > ?', DateTime.now).where(site: @site).order('end_date DESC').take(10)
  end

  def show
    @countdown = find params[:id]
    return if @countdown.nil?

    respond_to do |format|
      format.html
      format.json do
        render json: @countdown
      end
    end
  end

  def new
    @countdown = Countdown.new(twitter_id: session[:username])
  end
  
  def create
    @countdown = Countdown.new(countdown_params)
    @countdown.twitter_id = session[:username]
    @countdown.site = @site

    if @countdown.save
      redirect_to countdown_path(@countdown.name)
    else
      render 'new'
    end
  end

  def edit
    @countdown = find params[:id]
    return if @countdown.nil?
    redirect_to countdown_path(@countdown.name), alert: "This is not your countdown!" if @countdown.twitter_id != session[:username]
  end

  def update
    @countdown = Countdown.where(id: params[:id], site: @site).first
    return redirect_to root_url, alert: "Countdown does not exist." if @countdown.nil?
    redirect_to countdown_path(@countdown.name), alert: "This is not your countdown!" if @countdown.twitter_id != session[:username]

    if @countdown.update(countdown_params)
      redirect_to countdown_path(@countdown.name)
    else
      render 'edit'
    end
  end

  def destory
    @countdown = find params[:id]
    return if @countdown.nil?
    redirect_to countdown_path(@countdown.name), alert: "This is not your countdown!" if @countdown.twitter_id != session[:username]
    redirect_to countdown_path(@countdown.name), notice: "Currently do not support deleting."
  end

  private
    def countdown_params
      params.require(:countdown).permit(:name, :image, :title, :hashtag, :start_date, :end_date, :start_description, :end_description)
    end

    def find(name)
      countdown = Countdown.where(name: name.downcase, site: @site).first
      redirect_to root_url, alert: "Countdown #{name} does not exist." if countdown.nil?
      return countdown
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    session[:username] = auth_hash['info']['nickname']
    redirect_to new_countdown_path
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	include FoundationRailsHelper::FlashHelper
end

app/views/countdowns/_form.html.erb
<%= form_for @countdown, :html => { :multipart => true } do |f| %>
    <%= f.text_field :name %>
    <%= f.text_field :title %>
    <%= f.file_field :image %>
    <%= f.text_field :hashtag %>
    <%= f.datetime_field :start_date %>
    <%= f.datetime_field :end_date %>
    <%= f.text_area :start_description %>
    <%= f.text_area :end_description %>
    <%= f.submit "Save" %>
<% end %>

app/views/countdowns/disclaimer.html.erb
<div class="row">
	<div class="large-12 columns">
		<h1>Disclaimer of Liability</h1>
	</div>
</div>

<div class="row">
	<div class="large-12 columns">
		<p>
			THE SERVICE AND CONTENT FROM OR THROUGH THIS SITE ARE PROVIDED "AS-IS," "AS AVAILABLE," AND ALL WARRANTIES, EXPRESS OR IMPLIED, ARE DISCLAIMED (INCLUDING BUT NOT LIMITED TO THE DISCLAIMER OF ANY IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE). THE INFORMATION HEREIN MAY CONTAIN BUGS, ERRORS, PROBLEMS OR OTHER LIMITATIONS. THE OWNER OF THIS SITE ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY ERRORS OR OMISSIONS ON THIS SITE.
		</p>
	</div>
</div>

<div class="row">
	<div class="large-12 columns">
		&nbsp;
	</div>
</div>

<div class="row">
	<div class="large-12 columns">
		<%= form_for(:countdown, :url => new_countdown_path) do |f| %>
			<%= f.submit "Make your own!" %>
		<% end %>
		or <%= link_to "Go Back", root_path %>
	</div>
</div>

app/views/countdowns/edit.html.erb
<div class="row">
	<div class="large-12 columns">
		<h1><%= t :'form.edit' %></h1>
	</div>
</div>

<div class="row">
	<div class="large-12 columns">
		<%= render 'form' %>
	</div>
</div>

app/views/countdowns/index.html.erb
<div class="row">
	<div class="large-12 columns">
		<h1><%= t 'everyone.header' %></h1>
	</div>
</div>

<div class="row">
	<div class="large-12 columns">
		<h2>Make one for a friend!</h2>
	</div>
</div>

<div class="row">
	<div class="large-12 columns">
		<%= form_for(:countdown, :url => new_countdown_path) do |f| %>
			<%= f.submit "Let me make one!" %>
		<% end %>
	</div>
</div>
<div class="row">
	<% if @countdowns.count > 0 %>
		<table id="countdowns" class="large-12 columns">
			<thead>
				<tr>
					<th width="200">Name</th>
					<th>Time Left</th>
				</tr>
			</thead>
			<tbody>
				<% @countdowns.each do |countdown| %>
					<tr>
						<td><%= link_to countdown.title, countdown_path(countdown.name) %></td>
						<td data:end_date="<%= countdown.end_date.to_i * 1000 %>"></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	<% else %>
		<div class="large-12 columns">
			<p>No Countdowns in progress</p>
		</div>
	<% end %>
</div>

app/views/countdowns/new.html.erb
<div class="row">
	<div class="large-12 columns">
		<h1>New Countdown?</h1>
	</div>
</div>

<div class="row">
	<div class="large-12 columns">
      <%= form_for(@countdown) do |f| %>
        <%= f.text_field :name %>
        <%= f.text_field :title %>
        <%= f.text_field :image, :label => 'Facebook Username' %>
        <%= f.text_field :hashtag %>
        <%= f.datetime_field :start_date %>
        <%= f.datetime_field :end_date %>
        <%= f.text_area :start_description %>
        <%= f.text_area :end_description %>
        <%= f.submit "Create" %>
      <% end %>
	</div>
</div>

app/views/countdowns/show.html.erb
<div class="row">
	<div class="large-12 columns">
		<h1><%= @countdown.title %></h1>
	</div>
</div>

<div class="row">
	<div class="large-12 columns">
		<h3 id="description"></h3>
	</div>
</div>

<% if @countdown.twitter_id == session[:username] %>
	<div class="row">
		<div class="large-12 columns">
			<p><%= link_to "edit", edit_countdown_path(@countdown.name) %></p>
		</div>
	</div>
<% end %>

<div class="row">
	<div class="large-12 columns" id="iscoming">
		in <span id="remaining">...</span>
	</div>
</div>

<div class="row">
	<div class="large-12 columns">
		<%= image_tag @countdown.image.url(:medium), id: 'fader', class: @site, alt: @countdown.title %>
	</div>
</div>

<div class="row">
	<div class="large-12 columns" id="quote-container">
		<div id="quotes" class="cycle-slideshow" data-cycle-fx="scrollHorz" data-cycle-timeout="4000" data-cycle-slides="> div"></div>
	</div>
</div>

<div class="row">
	<div class="large-12 columns">
		&nbsp;
	</div>
</div>

<div class="row">
	<div class="large-12 columns">
		<%= form_for(:countdown, :url => new_countdown_path) do |f| %>
			<%= f.submit "Make your own!" %>
		<% end %>
		or <%= link_to "Go Back", root_path %>
	</div>
</div>

<script>
	var start, end, start_description, end_description, hashtags;

	start = new Date(<%= @countdown.start_date.to_i * 1000 %>);
	end = new Date(<%= @countdown.end_date.to_i * 1000 %>);

	start_description = "<%= @countdown.start_description %>";
	end_description = "<%= @countdown.end_description %>";

	hashtags = <%= @countdown.tweets.to_json.html_safe %>;
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="refresh" content="3000" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : t('title') %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <a href="https://github.com/williamsodell/GTFO-CTFI/"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png" alt="Fork me on GitHub"></a>

    <%= display_flash_messages %>

    <div class="row">
      <div class="large-12 columns">
        &nbsp;
      </div>
    </div>

    <div class="row">
      <div class="large-12 columns">
        &nbsp;
      </div>
    </div>
    
    <%= yield %>
    
    <footer class="row">
      <div class="large-4 columns">
        <p>
          © <%= Time.now.year %> BnC Group. All rights reserved.
        </p>
      </div>
      <div class="large-4 columns">
        <p>
          <%= link_to "Disclaimer", disclaimer_path %>
        </p>
      </div>

      <div class="large-4 columns">
        <p class="right">
          <%= @site %>.cc is a product of <a href="http://www.bncstudios.co" class="brand"><strong>BnC Group</strong></a>.
        </p>
      </div>
    </footer>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <%= javascript_include_tag "application" %>
  </body>
</html>